### PR TITLE
Add usb otg fs example

### PR DESCRIPTION
**Pull request by ant32**
I got the usb working on a NUCLEO-L4R5ZI

also needed to add stm32l4r5 to otg_fs feature list https://github.com/gauteh/stm32l4xx-hal/pull/1

Commented about trying to get usb working here https://github.com/stm32-rs/stm32l4xx-hal/pull/292

### CODE REVIEW

**Comment by gauteh** [comment]
Nice! That looks good. Would maybe make sense to use `ufmt` or something to write over USB?

**Comment by gauteh** [comment]
Would be happy with adding the NUCLEO next to the swan and rename the repo to something more stm32l4r5-* agnostic.

**Comment by ant32** [comment]
I copied the example from https://github.com/stm32-rs/stm32l4xx-hal/blob/master/examples/otg_fs_serial.rs and changed it a little to make it work

I'll look into ufmt

**Comment by ant32** [comment]
> Would be happy with adding the NUCLEO next to the swan and rename the repo to something more stm32l4r5-* agnostic.

It's probably good to just leave your examples dedicated to Swan. Pins, LEDs etc are different. People can find this repository when searching for l4r5 and then convert pins to match the Nucleo. I don't think people can get the Nucleo right now anyways.

**Pull request merged**
